#
# PHP 8.5
#

LoadFile "C:/xampp/php85/php8ts.dll"
LoadFile "C:/xampp/php85/libpq.dll"
LoadFile "C:/xampp/php85/libsqlite3.dll"

LoadModule php_module "C:/xampp/php85/php8apache2_4.dll"

<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>

<FilesMatch "\.phps$">
    SetHandler application/x-httpd-php-source
</FilesMatch>

<IfModule php_module>
    PHPINIDir "C:/xampp/php85"
</IfModule>

<IfModule mime_module>
    AddType text/html .php .phps
</IfModule>

ScriptAlias /php-cgi/ "C:/xampp/php85/"

<Directory "C:/xampp/php85">
    AllowOverride None
    Options None
    Require all denied

    <Files "php-cgi.exe">
        Require all granted
    </Files>
</Directory>
