#
# PHP 8.2
#

LoadFile "C:/xampp/php82/php8ts.dll"
LoadFile "C:/xampp/php82/libpq.dll"
LoadFile "C:/xampp/php82/libsqlite3.dll"

LoadModule php_module "C:/xampp/php82/php8apache2_4.dll"

<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>

<FilesMatch "\.phps$">
    SetHandler application/x-httpd-php-source
</FilesMatch>

<IfModule php_module>
    PHPINIDir "C:/xampp/php82"
</IfModule>

<IfModule mime_module>
    AddType text/html .php .phps
</IfModule>

ScriptAlias /php-cgi/ "C:/xampp/php82/"

<Directory "C:/xampp/php82">
    AllowOverride None
    Options None
    Require all denied

    <Files "php-cgi.exe">
        Require all granted
    </Files>
</Directory>
