#
# PHP 7.4
#

LoadFile "C:/xampp/php74/php7ts.dll"
LoadFile "C:/xampp/php74/libpq.dll"
LoadFile "C:/xampp/php74/libsqlite3.dll"

LoadModule php7_module "C:/xampp/php74/php7apache2_4.dll"

<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>

<FilesMatch "\.phps$">
    SetHandler application/x-httpd-php-source
</FilesMatch>

<IfModule php7_module>
    PHPINIDir "C:/xampp/php74"
</IfModule>

<IfModule mime_module>
    AddType text/html .php .phps
</IfModule>

ScriptAlias /php-cgi/ "C:/xampp/php74/"

<Directory "C:/xampp/php74">
    AllowOverride None
    Options None
    Require all denied

    <Files "php-cgi.exe">
        Require all granted
    </Files>
</Directory>
