[PHP]
engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
unserialize_callback_func =
serialize_precision = -1
disable_functions =
disable_classes =
zend.enable_gc = On
expose_php = On
max_execution_time = 30
max_input_time = 60
memory_limit = 128M
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
log_errors = On
html_errors = On
variables_order = "GPCS"
request_order = "GP"
post_max_size = 40M
default_mimetype = "text/html"
default_charset = "UTF-8"
file_uploads = On
upload_max_filesize = 40M
max_file_uploads = 20
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 60
extension_dir = "C:\xampp\php82\ext"
sys_temp_dir = "C:\xampp\tmp"
upload_tmp_dir = "C:\xampp\tmp"
session.save_path = "C:\xampp\tmp"
cgi.fix_pathinfo = 1

extension = bz2
extension = curl
extension = exif
extension = fileinfo
extension = ftp
extension = gd
extension = gettext
extension = mbstring
extension = mysqli
extension = openssl
extension = pdo_mysql
extension = pdo_sqlite
extension = sqlite3
extension = zip

curl.cainfo = "C:\xampp\php82\cacert.pem"
openssl.cafile = "C:\xampp\php82\cacert.pem"
